[2024-05-03T06:17:46.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T06:17:47.005+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_etl.send_email manual__2024-05-03T06:07:20.208728+00:00 [queued]>
[2024-05-03T06:17:47.019+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_etl.send_email manual__2024-05-03T06:07:20.208728+00:00 [queued]>
[2024-05-03T06:17:47.020+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-03T06:17:47.079+0000] {taskinstance.py:2327} INFO - Executing <Task(EmailOperator): send_email> on 2024-05-03 06:07:20.208728+00:00
[2024-05-03T06:17:47.088+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'exchange_rate_etl', 'send_email', 'manual__2024-05-03T06:07:20.208728+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rate_pipeline.py', '--cfg-path', '/tmp/tmpmigaqutx']
[2024-05-03T06:17:47.090+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T06:17:47.091+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask send_email
[2024-05-03T06:17:47.092+0000] {standard_task_runner.py:63} INFO - Started process 105 to run task
[2024-05-03T06:17:47.216+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_etl.send_email manual__2024-05-03T06:07:20.208728+00:00 [running]> on host 2189df070f97
[2024-05-03T06:17:47.327+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='exchange_rate_etl' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T06:07:20.208728+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T06:07:20.208728+00:00'
[2024-05-03T06:17:47.329+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T06:17:47.359+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-05-03T06:17:47.360+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-03T06:17:47.362+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-03T06:17:47.381+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T06:17:47.382+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2024-05-03T06:17:47.389+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=exchange_rate_etl, task_id=send_email, execution_date=20240503T060720, start_date=20240503T061747, end_date=20240503T061747
[2024-05-03T06:17:47.453+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task send_email (STARTTLS extension not supported by server.; 105)
[2024-05-03T06:17:47.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T06:17:47.509+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T06:17:47.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
